### ISSUE TITLE
Plugin incompatible with the latest Webstorm version 2019.2

### ISSUE THREAD

**Issue by oscarpenelo** [plamen-paskov/serverless-framework-gui#19]

**Comment by plamen-paskov** [comment]
Hi @oscarpenelo ,
Thanks for opening the issue!
I submitted the new version which add support for 2019.2 . It should be available in two business days. I will let you know once it's live.

**Comment by oscarpenelo** [comment]
Thanks!

**Comment by plamen-paskov** [comment]
The new version has been released!
